#!/usr/bin/python
import matplotlib.pyplot as plt
from PIL import Image
from numpy import asarray
from sys import argv

if __name__=='__main__':
    plt.subplots_adjust(left=0.0,right=1.0,bottom=0.0,top=1.0,wspace=0.0,hspace=0.0)
    plt.xticks(color="None")
    plt.yticks(color="None")
    plt.tick_params(length=0)
    im = Image.open(argv[1])
    im = asarray(im)
    plt.imshow(im)
    plt.show()
    exit()
